site_name: AWS Technical Essentials
site_description: Manual de estudio en español del curso AWS Technical Essentials
site_author: José Antonio Seguido Doblado
site_url: https://seguidodoblado.github.io/aws-technical-essentials/
repo_name: GitHub
repo_url: https://github.com/seguidodoblado/aws-technical-essentials

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Inicio: index.md

  - Guía del estudiante:
      - 00. Descripción general del curso: guia-del-estudiante/00-descripcion-general-del-curso.md
      